### ISSUE TITLE
quick todo

### ISSUE THREAD

**Issue by zenrabbit** [nargolg1/Animal-Behaviour-and-Climate-project#1]
- [x] rename repo again
- [x] track changes to be addressed in word doc
- [ ] add a few key pdfs
- [ ] add additional notes in a text file with ideas
- [ ] add deck
